name: ssp-dev
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.9
  - pip
  - psycopg2
  - pyarrow>=14
  - pandas>=1.5
  - numpy>=1.21
  - astropy>=5.0
  - scipy>=1.7
  - pyyaml>=6.0
  - tqdm>=4.0
  - jax
  - pytest>=8
  # Development tools
  - ipython
  - pip:
    - -e .[all]
